# Generated by Django 5.1.2 on 2024-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('publication_date', models.DateField(null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
    ]
